Feature 14 web api
Flexberry/NewPlatform.Flexberry.LogService pull request #16
Opened 2023-03-15 04:04 UTC by VChurekov

2023-03-15 05:14 UTC, bratchikov requested changes

2023-03-15 05:14 UTC, bratchikov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/HttpConfigurationExtensions.cs
> +                throw new ArgumentNullException(nameof(config), "Contract assertion not met: config != null");
Что за странное сообщение про контракт?

2023-03-15 05:14 UTC, bratchikov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/MapRouteRouteBuilderExtensions.cs
> +            var applicationPartManager = builder.ServiceProvider.GetRequiredService<ApplicationPartManager>();
var тут непонятен.

2023-03-15 05:14 UTC, bratchikov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/RequestsObjects/LogRequest.cs
> +    public class LogRequest
Нужны XML-комментарии.

2023-03-15 09:37 UTC, kuzkok commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +                        LogService.LogInfo(msg);
LogService надо через DI здесь получать, а не использовать статический экземпляр.

2023-03-15 09:47 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/HttpConfigurationExtensions.cs
> +            config.Routes.MapHttpRoute(routeName, "api/logs", defaults: new { controller = "Logs", action = "PostLog" });
А на что влияет routeName, зачем разработчику может понадобиться его указать? И может стоит дать возможность и url задавать прикладному разработчику?

2023-03-15 09:47 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/MapRouteRouteBuilderExtensions.cs
> +            var applicationPartManager = builder.ServiceProvider.GetRequiredService<ApplicationPartManager>();
Почему непонятен? `ApplicationPartManager` же

2023-03-15 09:47 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/MapRouteRouteBuilderExtensions.cs
> +            return builder.MapRoute(routeName, "api/logs", defaults: new { controller = "Logs", action = "PostLog" });
Аналогично может стоит дать возможность и url задавать

2023-03-15 09:47 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +    [Produces("application/json")]
А это необходимо? Вроде методы ничего не возвращают в теле ответа

2023-03-15 09:47 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +            string msg = JsonConvert.SerializeObject(request, settings);
Получается все поля LogRequest-а просто в message уйдут в таблице логов, разве нет? Мне казалось нужно часть полей раскладывать по соответствующим полям таблицы логов

2023-03-15 10:07 UTC, AntonIV8 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +            string msg = JsonConvert.SerializeObject(request, settings);
Возможно я не совсем понял вопрос.
Тут мы ориентировались в первую очередь на отправку в loki.
Сам logService в бд не записывает (не видел, чтобы у него эту функцию в проектах подключали), это делает Orm (таблица applicationLogs).

Тут мы сделали формат объекта с полями, аналогичными столбцам таблицы applicationLog.
В loki уйдет json в виде { 'category':'DEBUG'....'message':'само сообщ об ошибке'...}
и grafana сделает из него типа объект

2023-03-15 10:16 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +            string msg = JsonConvert.SerializeObject(request, settings);
То есть этот контроллер только в локи сможет писать, а в ApplicationLogs не сможет?

2023-03-15 10:27 UTC, AntonIV8 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +            string msg = JsonConvert.SerializeObject(request, settings);
Лог-сервис на основе log4net, он может писать в несколько мест в зависимости от аппендеров, которые в его конфиге накручены. Я как-то не видел, чтобы его на запись в БД настраивали. Обычно он пишет в консоль и файл, мы вот локи-аппендер еще добавили.

Запись логов в бд идет вообще в обход его, это просто стандартная запись через Store и Odata

2023-03-15 10:38 UTC, mao29 commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +            string msg = JsonConvert.SerializeObject(request, settings);
На большинстве некрупных проектов он в БД пишет. Тем более что при установке ORM в конфиг приложения автоматом AdoNetAppender добавляется. Но я сообразил, что запись отдельных полей в таблицу ApplicationLogs настраивалась как раз в конфигурации Appender-а самого, а не внутри LogService. Так что ок, вопрос снимается

2023-03-16 07:30 UTC, VChurekov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/HttpConfigurationExtensions.cs
> +                throw new ArgumentNullException(nameof(config), "Contract assertion not met: config != null");
Исправил.

2023-03-16 07:31 UTC, VChurekov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/RequestsObjects/LogRequest.cs
> +    public class LogRequest
Добавил.

2023-03-16 07:31 UTC, VChurekov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/HttpConfigurationExtensions.cs
> +            config.Routes.MapHttpRoute(routeName, "api/logs", defaults: new { controller = "Logs", action = "PostLog" });
Добавил routeTemplate в параметры.

2023-03-16 07:31 UTC, VChurekov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/Extensions/MapRouteRouteBuilderExtensions.cs
> +            return builder.MapRoute(routeName, "api/logs", defaults: new { controller = "Logs", action = "PostLog" });
Добавил routeTemplate в параметры.

2023-03-16 07:32 UTC, VChurekov commented on NewPlatform.Flexberry.LogService.WebApi/Controllers/LogsController.cs
> +    [Produces("application/json")]
Убрал.

2023-03-16 08:16 UTC, mao29 approved these changes

2023-03-16 10:28 UTC, merged